#!/usr/bin/env python3

import os

import gitignorefile
import requests


endpoint = "http://10.10.10.9:18981/upload"

root = os.path.dirname(os.path.abspath(__file__))
paths = []
for r, dd, ff in os.walk(root):
    dd[:] = [d for d in dd if not gitignorefile.ignored(os.path.join(r, d), is_dir=True)]
    for f in ff:
        path = os.path.join(r, f)
        if gitignorefile.ignored(path, is_dir=False):
            continue
        if not f.isupper():
            continue
        relative_path = os.path.join("UL", os.path.relpath(path, root))
        paths.append((relative_path, path))

max_size = max([len(p[0]) for p in paths])
for relative_path, path in sorted(paths):
    with open(path, "rb") as file:
        response = requests.put(endpoint, auth=("user", "password"), headers={"X-Destination-Path": relative_path}, data=file)
        assert response.status_code == 200, f"Failed to upload `{path}`: {response.status_code} {response.text.strip()}"
    print(relative_path.ljust(max_size), os.path.getsize(path))
